### ISSUE TITLE
Latest migrations and behind databases

### ISSUE THREAD

**Issue by nZac** [level12/keg-bouncer#2]
I don't think the `latest` functionality is going to work.

If my database is at V1 and Bouncer is at V3 when I run `alembic upgrade`, the call to `latest` is going to run against the wrong (and possibly conflicting) version. Keg would have to support migration plan resolution to make migrations a real possibility. 

In the mean time, I think a 1:1 mapping of Extension Migration:Application Migration would be best. You could have multiple extension migrations to one Application Migration, but that is the application developers choice.

**Comment by 3noch** [comment]
I don't quite understand everything you're saying, but I agree that `latest` is likely problematic. I think it would work _iff_ the application pins the version of KegBouncer to exactly one version. In my code, I'm actually importing `version_001` because I feared the same thing. I'll remove `latest`.

**Comment by 3noch** [comment]
If what you're saying is that an application should create a migration for every KegBouncer version that it wants to migrate, then I agree. And like you say, you could do multiple upgrades/downgrades in a single app migration. KegBouncer is merely giving you the ability to tie its migrations into yours without understanding the intricacies of each change.
